### ISSUE TITLE
problem with camera

### ISSUE THREAD

**Issue by TheFr0st3r** [ihrapsa/OctoWrt#12]
I can not use my camera, I do not know why but it does not work I also tried to enter the "link" obviously changing the ip address and everything but it continues not to work, but I am sure that the card detects the camera since I am confirmed by the plug in ... What can I d

**Comment by ihrapsa** [comment]
I think we fixed this on discord. By default mjpg-streamer is secured by user and pass setup in `/etc/config/mjpg-streamer`. Just comment those ore add them in your link`
