### ISSUE TITLE
Problem with Hue plugin install in octoprint

### ISSUE THREAD

**Issue by RobertHolscher** [ihrapsa/OctoWrt#15]
In the octowrt on the creality wifi box, i dont get the Hue plugins installed. There are 3 plugins in the repository but all fail. What can be the cause? Is there a workaround ? Please look at the attached messages. I notice that it tries to work with Wheel, resource. Is that the problem?
![63F73F02-9703-455E-810A-73920A8587E6](https://user-images.githubusercontent.com/44336407/155354580-09ede15c-946c-4650-b427-c94ddc31600d.png)
![D2437E23-4EFB-42B5-8099-34E275D05F6B](https://user-images.githubusercontent.com/44336407/155354589-c738909e-6f5b-44ae-8774-d5e3cdc6acc0.png)

**Comment by RobertHolscher** [comment]
Hereby the list of the tried plugins
![287FC70C-F4BE-4CDA-9A4B-38460671B96B](https://user-images.githubusercontent.com/44336407/155355319-4218e354-a5e5-4f9e-95aa-f78efda06fd9.png)

**Comment by RobertHolscher** [comment]
Hereby the logfile
[plugin_pluginmanager_console.log](https://github.com/ihrapsa/OctoWrt/files/8125742/plugin_pluginmanager_console.log)

**Comment by ihrapsa** [comment]
the issue is with the numpy module. I don't htink mips architecture is able to build that package from source. I don't see a precompiled official package either. Only way to install that would be if we cross compile it on a different machine. I cantry crosscompiling it for you these days.

**Comment by ihrapsa** [comment]
in the meantime try executing this `pip install --upgrade pip setuptools wheel` then try installing that plugin again

**Comment by RobertHolscher** [comment]
Thanks I will try this

Verstuurd vanaf mijn iPhone

Op 23 feb. 2022 om 16:56 heeft Iona Hrapsa ***@***.***> het volgende geschreven:

﻿
in the meantime try executing this pip install --upgrade pip setuptools wheel then try installing that plugin again

**Comment by RobertHolscher** [comment]
Hi 
I tried it and it still fails to install the plugin, however not on the same place in the installer. Now it ends with the message that the plug-in fails to install, look at the log for details. I will also try the other hue plug-ins later

Kind regards 
Robert

Verstuurd vanaf mijn iPhone

Op 23 feb. 2022 om 16:56 heeft Iona Hrapsa ***@***.***> het volgende geschreven:

﻿
in the meantime try executing this pip install --upgrade pip setuptools wheel then try installing that plugin again

**Comment by ihrapsa** [comment]
can you share the logs?

**Comment by RobertHolscher** [comment]
It is now sropping at download numpy
[plugin_pluginmanager_console 4.log](https://github.com/ihrapsa/OctoWrt/files/8128478/plugin_pluginmanager_console.4.log)

**Comment by ihrapsa** [comment]
is it hanging there, no error?

**Comment by RobertHolscher** [comment]
Correct

**Comment by duchengyao** [comment]
Build numpy will cost long time. For about one hour in raspberry pi. In Ubuntu, I will install numpy using apt-get.
