### ISSUE TITLE
firewall.getZoneColorStyle is not a function

### ISSUE THREAD

**Issue by rickasheye** [ihrapsa/OctoWrt#16]
Everytime i go to interfaces menu with this firmware now i see "firewall.getZoneColorStyle is not a function" seems like a openwrt issue.

**Comment by ihrapsa** [comment]
Do you have a screenshot?

**Comment by rickasheye** [comment]
it was having the issue before. but now honestly it works fine, dont know what i did but it before it would'nt stop doing it even after a reflash etc. but now it works properly?
