### ISSUE TITLE
Can I use Octoprint==1.8.0?

### ISSUE THREAD

**Issue by duchengyao** [ihrapsa/OctoWrt#22]
I'v noticed that the latest version is 1.8.0. Can I use this version?

**Comment by ihrapsa** [comment]
> I'v noticed that the latest version is 1.8.0. Can I use this version?

I haven't tested it yet. You can try it and report what dependencies break the install.

**Comment by duchengyao** [comment]
Thanks for reply. I'll try it.

Regards,
