### ISSUE TITLE
Cannot Access terminal

### ISSUE THREAD

**Issue by FabbroF** [ihrapsa/OctoWrt#24]
It seems that any attempt to connect to the terminal get denied.
No matter what brower is being used, or interface of method of connection.

**Comment by ihrapsa** [comment]
Could you be more specific? What terminal? Send some screenshots please

**Comment by FabbroF** [comment]
Service-> Terminal

**Comment by ihrapsa** [comment]
> Service-> Terminal

Send some screenshots please. Did you change the configs of the terminal service to use the client wifi network?
