### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by Darkstar83** [ihrapsa/OctoWrt#27]
❗ Check Releases page for binaries ❗

there is no such page, 

I am completeley new to Github, i cannot find the Releases page, Either the page is not there or i do not know how to navigate to said page

any assistance will be appreciated.

**Comment by ihrapsa** [comment]
it's right there on the right side panel of the main page. https://github.com/ihrapsa/OctoWrt/releases/tag/v1.0.0

**Comment by Darkstar83** [comment]
May I ask further questions if I get stuck somewhere through the install?

**Comment by Darkstar83** [comment]
How do I SSH onto it:  achieve step 4?
(https://github.com/ihrapsa/OctoWrt/tree/main/firmware)/OpenWrt_snapshot/

**Comment by ihrapsa** [comment]
> How do I SSH onto it: achieve step 4? (https://github.com/ihrapsa/OctoWrt/tree/main/firmware)/OpenWrt_snapshot/

for internet setup follt this: https://github.com/ihrapsa/OctoWrt#1-flash-openwrt-following-guide-here
no need to ssh. everything can be done using luci UI

**Comment by ihrapsa** [comment]
Io don't need to ssh anymore. Internet setup can be dune through luvi web ui. follow this: 
https://github.com/ihrapsa/OctoWrt#1-flash-openwrt-following-guide-here

**Comment by ihrapsa** [comment]
It's kind of a mess what you're doing there. What klipper firmware are you talking about? you can't flash klipper on the box. The box runs OpenWrt. Since the issue is opened on the OctoWrt page I reckon that you want to install octoprint. Did you follow the steps from the guide?

**Comment by Darkstar83** [comment]
Klipper with fluidd

**Comment by ihrapsa** [comment]
> Klipper with fluidd

This guide is for Octoprint. Check KlipperWrt repo for that

**Comment by Darkstar83** [comment]
Ok Thank you very much for all the help given. Further help will be obtained from the Klipper Repositories. Have a blessed day.

**Comment by ihrapsa** [comment]
you too! check out the discord server for further help
