### ISSUE TITLE
Problem config camera

### ISSUE THREAD

**Issue by Pepitoo597** [ihrapsa/OctoWrt#29]
Hello I would like to configure my Logitech C160 camera which is compatible with mjpg-streamer but the camera lags so I would like to solve the problem but I don't know which file to go to please

**Comment by ihrapsa** [comment]
Edit fps line inside `/etc/config/mjpg-streamer` file. Don't go higher than 15fps  if you use the box to stream gcode as well. Or experiment with it

**Comment by Pepitoo597** [comment]
Ok thank you, after testing my camera still has this latency problem, I think it is better to change the camera. Do you have a camera to recommend to me?

**Comment by ihrapsa** [comment]
Wait, high latency or low framerate? Two different things.

**Comment by Pepitoo597** [comment]
I don't really know how to explain it in fact when the printer makes a movement the camera will take a while before seeing the printer move it is not fluid.

**Comment by ihrapsa** [comment]
check the difference between latency and framerate. what framerate did you set inside mjpg-streamer file?

**Comment by Pepitoo597** [comment]
I set the framerate to 15

**Comment by ihrapsa** [comment]
do `cat /etc/config/mjpg-streamer`and show me

**Comment by Pepitoo597** [comment]
![Capture d’écran 2022-08-18 194659](https://user-images.githubusercontent.com/111463478/185461166-bc04bfde-6cc7-45ed-82a8-d76366a88f21.png)

**Comment by ihrapsa** [comment]
Frame rate is ok. Can you do short video with printer and stream at the same time to see what's the issue?
