### ISSUE TITLE
Restore CrealityBox V2.0

### ISSUE THREAD

**Issue by Nico4589** [ihrapsa/OctoWrt#38]
Hi, is there a way to reset the Creality Box V2.0 and start the procedure from scratch? Thank you

**Comment by ihrapsa** [comment]
> Hi, is there a way to reset the Creality Box V2.0 and start the procedure from scratch? Thank you

If you want to start over you don’t need to restore to stock. The simplest way is to hold the reset button for about 6 sec and wait a minute or so. The OpenWrt on it will restore to default.

**Comment by Nico4589** [comment]
Thanks for the help, I did it.
