### ISSUE TITLE
Error - not downloading package

### ISSUE THREAD

**Issue by andrewb2102** [ihrapsa/OctoWrt#5]
root@KlipperWrt:~# opkg update
Downloading https://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/packages/Packages.gz
Error relocating /usr/bin/wget: __gmtime64: symbol not found
Error relocating /usr/bin/wget: __localtime64_r: symbol not found
Error relocating /usr/bin/wget: __select_time64: symbol not found
Error relocating /usr/bin/wget: __setitimer_time64: symbol not found
Error relocating /usr/bin/wget: __lstat_time64: symbol not found
Error relocating /usr/bin/wget: __clock_getres_time64: symbol not found
Error relocating /usr/bin/wget: __localtime64: symbol not found
Error relocating /usr/bin/wget: __stat_time64: symbol not found
Error relocating /usr/bin/wget: __fstat_time64: symbol not found
Error relocating /usr/bin/wget: __utime64: symbol not found
Error relocating /usr/bin/wget: __clock_gettime64: symbol not found
Error relocating /usr/bin/wget: __gmtime64_r: symbol not found
Error relocating /usr/bin/wget: __time64: symbol not found
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/packages/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/Packages.gz
Error relocating /usr/bin/wget: __gmtime64: symbol not found
Error relocating /usr/bin/wget: __localtime64_r: symbol not found
Error relocating /usr/bin/wget: __select_time64: symbol not found
Error relocating /usr/bin/wget: __setitimer_time64: symbol not found
Error relocating /usr/bin/wget: __lstat_time64: symbol not found
Error relocating /usr/bin/wget: __clock_getres_time64: symbol not found
Error relocating /usr/bin/wget: __localtime64: symbol not found
Error relocating /usr/bin/wget: __stat_time64: symbol not found
Error relocating /usr/bin/wget: __fstat_time64: symbol not found
Error relocating /usr/bin/wget: __utime64: symbol not found
Error relocating /usr/bin/wget: __clock_gettime64: symbol not found
Error relocating /usr/bin/wget: __gmtime64_r: symbol not found
Error relocating /usr/bin/wget: __time64: symbol not found
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/Packages.gz
Error relocating /usr/bin/wget: __gmtime64: symbol not found
Error relocating /usr/bin/wget: __localtime64_r: symbol not found
Error relocating /usr/bin/wget: __select_time64: symbol not found
Error relocating /usr/bin/wget: __setitimer_time64: symbol not found
Error relocating /usr/bin/wget: __lstat_time64: symbol not found
Error relocating /usr/bin/wget: __clock_getres_time64: symbol not found
Error relocating /usr/bin/wget: __localtime64: symbol not found
Error relocating /usr/bin/wget: __stat_time64: symbol not found
Error relocating /usr/bin/wget: __fstat_time64: symbol not found
Error relocating /usr/bin/wget: __utime64: symbol not found
Error relocating /usr/bin/wget: __clock_gettime64: symbol not found
Error relocating /usr/bin/wget: __gmtime64_r: symbol not found
Error relocating /usr/bin/wget: __time64: symbol not found
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/luci/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/Packages.gz
Error relocating /usr/bin/wget: __gmtime64: symbol not found
Error relocating /usr/bin/wget: __localtime64_r: symbol not found
Error relocating /usr/bin/wget: __select_time64: symbol not found
Error relocating /usr/bin/wget: __setitimer_time64: symbol not found
Error relocating /usr/bin/wget: __lstat_time64: symbol not found
Error relocating /usr/bin/wget: __clock_getres_time64: symbol not found
Error relocating /usr/bin/wget: __localtime64: symbol not found
Error relocating /usr/bin/wget: __stat_time64: symbol not found
Error relocating /usr/bin/wget: __fstat_time64: symbol not found
Error relocating /usr/bin/wget: __utime64: symbol not found
Error relocating /usr/bin/wget: __clock_gettime64: symbol not found
Error relocating /usr/bin/wget: __gmtime64_r: symbol not found
Error relocating /usr/bin/wget: __time64: symbol not found
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/routing/Packages.gz
Error relocating /usr/bin/wget: __gmtime64: symbol not found
Error relocating /usr/bin/wget: __localtime64_r: symbol not found
Error relocating /usr/bin/wget: __select_time64: symbol not found
Error relocating /usr/bin/wget: __setitimer_time64: symbol not found
Error relocating /usr/bin/wget: __lstat_time64: symbol not found
Error relocating /usr/bin/wget: __clock_getres_time64: symbol not found
Error relocating /usr/bin/wget: __localtime64: symbol not found
Error relocating /usr/bin/wget: __stat_time64: symbol not found
Error relocating /usr/bin/wget: __fstat_time64: symbol not found
Error relocating /usr/bin/wget: __utime64: symbol not found
Error relocating /usr/bin/wget: __clock_gettime64: symbol not found
Error relocating /usr/bin/wget: __gmtime64_r: symbol not found
Error relocating /usr/bin/wget: __time64: symbol not found
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/routing/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/telephony/Packages.gz
Error relocating /usr/bin/wget: __gmtime64: symbol not found
Error relocating /usr/bin/wget: __localtime64_r: symbol not found
Error relocating /usr/bin/wget: __select_time64: symbol not found
Error relocating /usr/bin/wget: __setitimer_time64: symbol not found
Error relocating /usr/bin/wget: __lstat_time64: symbol not found
Error relocating /usr/bin/wget: __clock_getres_time64: symbol not found
Error relocating /usr/bin/wget: __localtime64: symbol not found
Error relocating /usr/bin/wget: __stat_time64: symbol not found
Error relocating /usr/bin/wget: __fstat_time64: symbol not found
Error relocating /usr/bin/wget: __utime64: symbol not found
Error relocating /usr/bin/wget: __clock_gettime64: symbol not found
Error relocating /usr/bin/wget: __gmtime64_r: symbol not found
Error relocating /usr/bin/wget: __time64: symbol not found
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/telephony/Packages.gz

**Comment by ihrapsa** [comment]
show me `cat /etc/opkg/distfeeds.conf`
