### ISSUE TITLE
error when installing octoprint 1.6.1

### ISSUE THREAD

**Issue by drakengard780** [ihrapsa/OctoWrt#6]
hi, i have a problem , when i arrive to install octoprint compare an error:

ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jqid1cfe/regex_e2f3b767df6b4c37b68b350b894d6d2e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jqid1cfe/regex_e2f3b767df6b4c37b68b350b894d6d2e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zpl7kz4f/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/regex Check the logs for full command output.

what can i do ? a read all step in wiki and video tutorial .

**Comment by ihrapsa** [comment]
You sure you followed these steps?
![image](https://user-images.githubusercontent.com/40600040/149631396-523712e1-04f2-4b42-81c6-f1e6bec5ca79.png)

**Comment by drakengard780** [comment]
absolutely

**Comment by drakengard780** [comment]
can i retry?

**Comment by drakengard780** [comment]
[https://ibb.co/5MrxbBN](url)

**Comment by drakengard780** [comment]
<img width="760" alt="Senza titolo" src="https://user-images.githubusercontent.com/38538754/149632139-d2020da8-9adf-4cad-a3d8-8a76959e3edd.png">

**Comment by drakengard780** [comment]
if i reinstall python dependence compare thise warning 
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by ihrapsa** [comment]
> absolutely

not the octoprint command just the commands I screenshot above.

**Comment by ihrapsa** [comment]
> if i reinstall python dependence compare thise warning
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

ignore that for the time being

**Comment by drakengard780** [comment]
ok i insert second command all ok
i try to reinstall octoprint

**Comment by drakengard780** [comment]
ok now install it but if go to ip:5000 stock to load same dead

**Comment by drakengard780** [comment]
ok now all work ...to start up to 10 minute. but now now all work eccept path of webcam , if test it say path not exist

**Comment by ihrapsa** [comment]
> ok now all work ...to start up to 10 minute. but now now all work eccept path of webcam , if test it say path not exist

what webcam are you using? is it plugged? what's the path set in octoprint?

**Comment by drakengard780** [comment]
i not have for now webcam arrive tommorrow. but i set the path and install all the code in wiki guide but i not have the path

**Comment by ihrapsa** [comment]
> i not have for now webcam arrive tommorrow. but i set the path and install all the code in wiki guide but i not have the path

there's no webcam path if you don't have webcam. what's the path that you set? show me

**Comment by drakengard780** [comment]
Ok thank you this issue resolve
